### ISSUE TITLE
Resulting File

### ISSUE THREAD

**Issue by JoshPhillips59** [carbonplan/bigcoast-project-boundary#2]
This is super interesting, and could be helpful to process a bunch of PDD in bulk.....but @badgley can you please add the resulting file to the repo, please :D

**Comment by badgley** [comment]
Thanks, @JoshPhillips59 - added to the README, but here's a copy of the link: https://carbonplan-forest-offsets.s3.us-west-1.amazonaws.com/offsets-project-boundaries/inferred_boundary.json
